### Makefile.inc --- LtxPkg configuration

## Copyright (C) 2009, 2017 Didier Verna

## Author: Didier Verna <didier@didierverna.net>

## This file is part of FiXme.

## FiXme may be distributed and/or modified under the conditions of the LaTeX
## Project Public License, either version 1.3 of this license or (at your
## option) any later version.  The latest version of this license is in
## http://www.latex-project.org/lppl.txt and version 1.3 or later is part of
## all distributions of LaTeX version 2005/12/01 or later.

## FiXme consists of the files listed in the file `README'.


### Commentary:


### Code:

TEXMFDIR  := ${HOME}/.texmf
AUCTEXDIR := ${HOME}/etc/auctex

DST_EMPTY_DIRS := themes layouts layouts/env layouts/target

### Makefile.inc ends here
