### Makefile.inc --- LtxPkg configuration

## Copyright (C) 2009 Didier Verna

## Author:        Didier Verna <didier@lrde.epita.fr>
## Maintainer:    Didier Verna <didier@lrde.epita.fr>
## Created:       Thu Aug 20 17:45:34 2009
## Last Revision: Thu Aug 20 17:53:25 2009


### Commentary:

## Contents management by FCM version 0.1.


### Code:

TEXMFDIR  := ${HOME}/.texmf
AUCTEXDIR := ${HOME}/etc/auctex

DST_EMPTY_DIRS := themes layouts layouts/env layouts/target

### Makefile.inc ends here
